module Help where

import Defaults

-- |  Key bindings in simple textual tabular format.
help :: String
help =
  unlines
    [ "The default modifier key is 'super'. Default keybindings:"
    , ""
    , "-- launching and killing programs"
    , "mod-Shift-Enter  Launch terminal emulator"
    , "mod-o            Launch drun"
    , "mod-Shift-o      Launch run"
    , "mod-Alt-o        Connect to officeVPN"
    , "mod-Shift-c      Close/kill the focused window"
    , "mod-Alt-x        xkill"
    , "mod-Alt-k        Display Keyboardio Atreus layout image"
    , "mod-Space        Rotate through the available layout algorithms"
    , "mod-Shift-Space  Reset the layouts on the current workSpace to default"
    , "mod-n            Resize/refresh viewed windows to the correct size"
    , "mod-Shift-b      Launch browser: " <> myBrowser
    , "mod-Shift-n      Launch file manager: " <> myFileManager
    , "mod-v            Paste selection"
    , -- , "mod-s            Enable side bar"
      -- , "mod-Shift-s      Disable side bar"
      -- , "mod-z            Enable inhibitor"
      -- , "mod-Shift-z      Disable inhibitor"
      -- , "mod-Shift-a      Launch rofi-clipboardy"
      "mod-c            Show clipboard history (greenclip)"
    , "PrintScrn        Screen capture (selection) to /tmp + copy to clipboard"
    , "mod-PrintScrn    Screen capture (entire screen) to /tmp + copy to clipboard"
    , ""
    , "-- move focus up or down the window stack"
    , "mod-Tab        Move focus to the next window"
    , "mod-Shift-Tab  Move focus to the previous window"
    , "mod-j          Move focus to the next window"
    , "mod-k          Move focus to the previous window"
    , -- , "mod-m          Move focus to the master window"
      ""
    , "-- modifying the window order"
    , "mod-Return   Swap the focused window and the master window"
    , "mod-Shift-j  Swap the focused window with the next window"
    , "mod-Shift-k  Swap the focused window with the previous window"
    , ""
    , "-- resizing the master/slave ratio"
    , "mod-h  Shrink the master area"
    , "mod-l  Expand the master area"
    , ""
    , "-- Current window toggles"
    , "mod-f        Toggle full screen"
    , "mod-Shift-f  Toggle floating layer"
    , ""
    , "-- warpd - virtual mouse pointer"
    , "mod-m        normal mode"
    , "mod-Shift-m  hint2 mode"
    , ""
    , "-- increase or decrease number of windows in the master area"
    , "mod-(,)   Increment the number of windows in the master area"
    , "mod-(.)   Deincrement the number of windows in the master area"
    , ""
    , "-- magnifier"
    , "mod-Ctrl-(=) Magnify more"
    , "mod-Ctrl-(-) Magnify less"
    , "mod-Ctrl-o Toggle magnify on"
    , "mod-Ctrl-O Toggle magnify off"
    , "mod-Ctrl-m Toggle magnify on/off"
    , ""
    , "-- quit or restart"
    , "mod-Shift-q  Launch power menu"
    , "mod-Shift-l  Lock screen"
    , "mod-q        Restart xmonad"
    , "mod-[1..9]   Switch to workSpace N"
    , ""
    , "-- Workspaces & screens"
    , "mod-Shift-[1..9]   Move client to workspace N"
    , "mod-{we,r}        Switch to physical/Xinerama screens 1, 2, or 3"
    , "mod-Shift-{we,r}  Move client to screen 1, 2, or 3"
    , ""
    , "-- Mouse bindings: default actions bound to mouse events"
    , "mod-button1  Set the window to floating mode and move by dragging"
    , "mod-button2  Raise the window to the top of the stack"
    , "mod-button3  Set the window to floating mode and resize by dragging"
    , ""
    , "-- Launch applications"
    , -- , "mod-Shift-p  Launch Polysun"
      "mod-Alt-b    Launch Bluetooth Manager"
    , "mod-Alt-v    Launch PulseAudio Volume Control"
    , "mod-Shift-i  Launch Inkscape"
    , "mod-Shift-k  Launch Keepass"
    , "mod-Shift-y  Launch yubioath-desktop"
    , "mod-Alt-k    Show keyboardio layout"
    , ""
    , "-- Search"
    , "mod-Alt-h        Hoogle search"
    , -- , "mod-Alt-H        Hoogle (ners) search"
      "mod-Alt-f        Flora search"
    , "mod-Alt-n        NixOS search"
    , -- , "mod-Alt-N        Noogle search"
      -- , "mod-Alt-K        Kagi search"
      "mod-Alt-g        Kagi search"
      -- , "mod-Alt-G        GitHub search"
    ]
