{
  cd = "z";
  bd = "prevd";
  nd = "nextd";
  eza = "eza --icons --git";
  ls = "eza --icons --git";
  la = "eza --icons --git -a";
  ll = "ls --icons --git -l";
  lt = "ls --icons --tree";
  ltg = "lt --git";
  lta = "lt -a";
  ltl = "lt -l";
  lla = "ls --icons --git -al";
  grep = "rg";
  cat = "bat --style=plain";
  du = "dust";
  ps = "procs";
  cloc = "tokei";
  top = "btm";
  htop = "btm";
  mkdir = "mkdir -p";
  vi = "nvim";
  vim = "nvim";
  nv = "neovide";
  ":e" = "nvim";
  ":q" = "exit";
  ":qa" = "exit";
  ":x" = "exit";
  ":wq" = "exit";
  ":w" = "cowsay 'You are not in neovim anymore.'";
  ":wa" = "cowsay 'You are not in neovim anymore.'";
  neogit = "nvim -c :Neogit";
  ngit = "nvim -c :Neogit";
  diffview = "nvim -c :DiffviewOpen";
  ndiff = "nvim -c :DiffviewOpen";
  nlog = "nvim -c :DiffviewFileHistory";
}
