{
  cd = "z";
  bd = "prevd";
  nd = "nextd";
  exa = "exa --icons --git";
  ls = "exa --icons --git";
  la = "exa --icons --git -a";
  ll = "ls --icons --git -l";
  lt = "ls --icons --tree";
  ltg = "lt --git";
  lta = "lt -a";
  ltl = "lt -l";
  lla = "ls --icons --git -al";
  grep = "rg";
  cat = "bat --style=plain";
  du = "dust";
  ps = "procs";
  cloc = "tokei";
  top = "btm";
  htop = "btm";
  mkdir = "mkdir -p";
  vi = "nvim";
  vim = "nvim";
  nv = "neovide";
  ":w" = "cowsay 'You are not in neovim anymore.'";
  ":wa" = "cowsay 'You are not in neovim anymore.'";
  ":wq" = "cowsay 'You are not in neovim anymore.'";
  ":q" = "cowsay 'You are not in neovim anymore.'";
  ":qa" = "cowsay 'You are not in neovim anymore.'";
  ":x" = "cowsay 'You are not in neovim anymore.'";
}
